### ISSUE TITLE
C++14 code but compiled with -std=c++11 flag

### ISSUE THREAD

**Issue by slokhorst** [eScatter/e-scatter#14]
It is impossible to build the project since some C++14 code was introduced but GCC is set to C++11 mode. We cannot switch the entire project to C++14 since CUDA doesn't support that. Is it a good idea to mix C++11 and C++14? (different compiler flags for different subdirectories/libraries)

**Comment by jhidding** [comment]
Ok, if I'm correct, the C++14 code only affects the `cstool` component. It should not be a problem to get it to compile. I'm thinking about translating the cstool code to Python for easier maintainability later on. But this will have to happen in september. The relevant code concerns the use of std::experimental::optional container. Its interface is similar (if not identical) to boost::optional.
Also, I think it should be Ok to link C++11 and  C++14 code together.

**Comment by slokhorst** [comment]
If it will not introduce any problems, switching all non-CUDA to C++14 mode will probably will be the easiest and most future-proof. CUDA will probably support it in the future anyway (unfortunately not yet with the upcoming CUDA 8.0).

About cstool: I did it in C++ because it has to handle/interpolate pretty large tables, but Python might do fine as well. The current plotting method with GNUplot is not ideal, Python might be able to handle it better.

I'll try to get the build working and push a fix today.

**Comment by slokhorst** [comment]
Easier than expected: #15 fixes it for me.
